name: Close inactive issues and PRs
on:
  schedule:
    - cron: "21 1 * * 1"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v8
        with:
          days-before-issue-stale: 45
          days-before-issue-close: 30
          stale-issue-label: "Pending closure"
          close-issue-label: "Closed due to inactivity"
          stale-issue-message: "This issue is stale because it has been open for 45 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 30 days since being marked as stale."
          exempt-all-issue-assignees: true
          days-before-pr-stale: 45
          days-before-pr-close: 30
          stale-pr-label: "Pending closure"
          close-pr-label: "Closed due to inactivity"
          stale-pr-message: "This PR is stale because it has been open for 45 days with no activity."
          close-pr-message: "This PR was closed because it has been inactive for 30 days since being marked as stale."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
